export const ADD_CONTAINER = 'ADD_CONTAINER'
export const ADD_WORKSPACE = 'ADD_WORKSPACE'

export const CHANGE_WORKSPACE = 'CHANGE_WORKSPACE'
export const CREATE_WORKSPACE = 'CREATE_WORKSPACE'

export const CHANGE_CONTAINER = 'CHANGE_CONTAINER'
export const DELETE_CONTAINER = 'DELETE_CONTAINER'
export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'